### ISSUE TITLE
第七题：描述 CSS 的权重计算规则

### ISSUE THREAD

**Issue by guokangf** [guokangf/Daily#7]
> 描述 CSS 的权重计算规则

```html
<div class="red blue">啥颜色</div>
<div class="blue red">啥颜色</div>
```

```css
.red { color: red; }
.blue { color: blue; }
```

两个 div 内容的颜色是什么？
